name: "📖 Documentation Issue"
description: Report incorrect, missing, or unclear documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our docs! Let us know what needs fixing or expanding.

  - type: textarea
    id: what
    attributes:
      label: What Needs Improvement
      description: Which section, page, or area of the documentation is affected?
      placeholder: "The installation section in README.md doesn't mention ..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Changes
      description: Describe the correction or addition you'd like to see.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Links, screenshots, or any other helpful context.
    validations:
      required: false
